### PR TITLE
Updated .inx files to fix issues with menu

### PR DESCRIPTION
**Pull request by bri-huang**
Updated the inx file to allow for population of the menu drop-down for Inkscape 1.0 <beta>.

### CODE REVIEW

**Comment by paulh-rnd** [comment]
Thanks for the PR. I'm not entirely sure what menu issues you're referring to, I didn't have any trouble with the extension appearing in the menu for Inkscape 1.0. Can you please elaborate?

**Comment by bri-huang** [comment]
I should have updated my Inkscape version and re-tested before making the
PR. I was running Inkscape 1.0beta1 (fe3e306, 2019-09-17) and the menus
weren't showing up. I updated to the May 2020 release, and it looks like it
works fine now. Sorry about that. Disregard this PR.

[image: image.png]


[image: image.png]

**Comment by paulh-rnd** [comment]
No problem, thanks!

**Comment by paulh-rnd** [comment]
Oh, I might also mention that I've been making some changes in the beta branch, including moving the extension to a CNC Tools submenu. This is because I've been able to get dog bone corners working for milling, so it's no longer just for lasers :) there are still several issues that I haven't had time to fix, but check it out and let me know what you think.

**Comment by bri-huang** [comment]
Cool. I'll check it out. Thanks!

**Pull request closed without merging**
