### PR TITLE
Updates to get plugin to work in Inkscape 1.0 Beta

### PR DESCRIPTION
**Pull request by mwinoto**
I haven't tested this extensively yet, all I know is that I can generate boxes in the latest Inkscape beta on MacOS Catalina

### CODE REVIEW

**Comment by mwinoto** [comment]
No response on this so I'm closing it.

**Comment by paulh-rnd** [comment]
So sorry @mwinoto, I've just been through a house sale and move, new baby and job change, all in the last month. I'm really grateful for what you've done, it's a massive contribution. I'm going to try and look at it next week. Sorry again for the delay.

**Comment by mwinoto** [comment]
Hey, no obligation to look at my changes. I'm happy to just fork and keep working on it as I need to.

**Comment by samanthasmiles** [comment]
Updates appreciated!

**Pull request closed without merging**
